site_name: PET Detector Monte Carlo Tutorial
nav:
  - Home: index.md
  - Background: background.md
  - Setup: setup.md
  - Simulation: simulation.md
  - Data Analysis & Imaging: analysis.md
  - Explore Further: explore.md

theme:
  name: mkdocs