site_name: PET Detector Monte Carlo Tutorial
nav:
  - Home: index.md
  - Background: background.md
  - Setup: setup.md
  - Step-by-Step Guide: tutorial.md
  - Data Analysis: analysis.md
  - Explore Further: explore.md

theme:
  name: mkdocs